package(
    default_visibility = ["//visibility:public"],
)

cc_library(
  name = "terrace_graph",
  hdrs = ["terrace_graph.h"],
  deps = [
    "@cpma//PMA:cpma",
    "@cpma//PMA:pcsr",
    "@CPAM//cpam",
  ],
)
